### ISSUE TITLE
PantherHackers on the Front Page Twice

### ISSUE THREAD

**Issue by bcabio** [PantherHackers/rails_site#19]
Just a design thing that kind of bugged me from the beginning but should PantherHackers be on the front page twice and in two different styles? It feels redundant.

**Comment by ferrerluis** [comment]
Agreed @bcabio. This has to do with #13. Navbar would be changed to not have the big logo in the middle. Then words in the middle of the page would be replaced by the two-line PH logo

**Comment by ferrerluis** [comment]
Refer to #13
