### ISSUE TITLE
Navigation bar currently merged with main area

### ISSUE THREAD

**Issue by sungjkim34** [PantherHackers/rails_site#20]
The navbar is currently nested within the same div as the main 'pitch-group' ("PantherHackers
Simple Solutions For Complex Problems" text area) as well as the 'subscribe-form'. 
I feel that there should be a redo of the layouts from the ground up.
Even if the original design is kept, the layouts of the divs and stylings should be reconstructed.

**Comment by ferrerluis** [comment]
Being fixed on #21
